### ISSUE TITLE
Find a generic way for matching the port by the endpoint lister instead of port name 

### ISSUE THREAD

**Issue by nader-ziada** [knative-extensions/net-gateway-api#668] opened 2024-04-09 20:33 UTC
As a follow up to PR #658 which adds the port names used by contour, we need a general way of solving this that isn't specific to an implementation.

The code matching on the port name on the endpoints seems to be different between implementations, so might be a good idea to investigate using the K8s service or something else instead

**Comment by dprotaso** [comment] 2024-04-09 20:35
Dupe of https://github.com/knative-extensions/net-gateway-api/issues/663

**Closed by dprotaso** 2024-04-09 20:35 UTC
