### ISSUE TITLE
[Upstream] Enable > 2k TLS Services

### ISSUE THREAD

**Issue by carlisia** [knative-extensions/net-gateway-api#368] opened 2022-08-10 15:47 UTC
Ref.:nhttps://github.com/kubernetes-sigs/gateway-api/discussions/1246.

**Comment by dprotaso** [comment] 2023-02-08 16:02
/lifecycle frozen

I've created a GEP issue to help address this - https://github.com/kubernetes-sigs/gateway-api/issues/1713

**Comment by dprotaso** [comment] 2024-04-02 17:58
Closing as duplicate of https://github.com/knative-extensions/net-gateway-api/issues/363

**Closed by dprotaso** 2024-04-02 17:58 UTC
Labels: lifecycle/frozen, upstream/gateway
