### ISSUE TITLE
[Upstream] Better management of `Spec.Listeners`

### ISSUE THREAD

**Issue by carlisia** [knative-extensions/net-gateway-api#363] opened 2022-08-10 15:40 UTC
Ref.: https://github.com/kubernetes-sigs/gateway-api/discussions/1248.

**Comment by dprotaso** [comment] 2023-02-08 16:02
/lifecycle frozen

I've created a GEP issue to help address this - https://github.com/kubernetes-sigs/gateway-api/issues/1713

**Comment by dprotaso** [comment] 2024-04-02 18:00
Clsoing as a dupe of https://github.com/knative-extensions/net-gateway-api/issues/317

**Closed by dprotaso** 2024-04-02 18:00 UTC
Labels: lifecycle/frozen, upstream/gateway
